### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Dimitar5555** [rlemon/Notifier.js#6]
This is what I get when I try it in Firefox ESR 52.0.2. The script doesn't work.
`TypeError: document.body is null`
`TypeError: Notifier is undefined`
On your site(http://rlemon.github.io/Notifier.js/) it works..

**Comment by rlemon** [comment]
If it works on the website then I'm suspect to think you're implementing it incorrectly. Can you show me where you include the script vs where you call it? Sounds like you're including it before the DOM is parsed.

**Comment by Dimitar5555** [comment]
`<script src="Notifier.js"></script>`
`<button onclick="Notifier.success(text, title);">d</button>`
That's the code but it doesn't work. Do I need to add something else?

**Comment by Dimitar5555** [comment]
I fount the bug. I needed to place <script> at the bottom of the page. I don't know why but it worked.

**Comment by rlemon** [comment]
That would mean it was included before the DOM was ready. 

I should update the README to mention that it doesn't wrap itself in a domready.
