### ISSUE TITLE
Problems with z-index

### ISSUE THREAD

**Issue by Dimitar5555** [rlemon/Notifier.js#7]
After some time of using, for some users the `<section id="alertify-logs">` doesn't hide. Because of this and its z-index, it causes that you can't on anything behind it. After a refresh it fixes.

Also for some other reason it is more common to gecko powered browsers(firefox, waterfox..) or I should say that it is only with them.

**Comment by rlemon** [comment]
can you make an example of the notifications not disappearing? I've never seen this behaviour.

**Comment by Dimitar5555** [comment]
I mean the invisible box shows and block on display: block

**Comment by rlemon** [comment]
There should be no 'blocks' left behind. The notification container (unless you set a size to it) should have no height/width when there are no elements in it. 

https://github.com/rlemon/Notifier.js/blob/master/Notifier.js#L16 and here you can see at the end of the fade out they should remove themselves. 

have you changed any of the default styles?

**Comment by Dimitar5555** [comment]
No, but I use the bootstrap.css, bootstrap.js and the bootstrap for this plugin.

**Comment by rlemon** [comment]
I'm not sure what that implies

**Comment by Dimitar5555** [comment]
After all the problem is that `<section id="alertify-logs"></section>` gets from somewhere fixed width, height and `display: block;`

**Comment by rlemon** [comment]
I have no idea what you've modified from my script to make that happen unless you make an example. The script creates its own container and appends it to the DOM. This sounds to me like you've made some breaking changes.

**Comment by Dimitar5555** [comment]
I haven't made any changes https://github.com/Dimitar5555/WaterCompany/blob/master/js/alertify.min.js

**Comment by rlemon** [comment]
alertify is not my script. -_-
